### ISSUE TITLE
bdf_lexer not available

### ISSUE THREAD

**Issue by ConnorRigby** [luisgabrielroldan/chisel#4]
```elixir
(UndefinedFunctionError) function :bdf_lexer.string/1 is undefined (module :bdf_lexer is not available)
```

I think you need to add the `src` folder to the hex package.

**Comment by luisgabrielroldan** [comment]
:O Right! Anyway, I'm moving out from the yecc and leex, Hopefully I can release a new version today with a new parser. Thanks @ConnorRigby !!
